services:
  - type: web
    name: csrms
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
